--
-- PostgreSQL database dump
--

\restrict xcK3cXF5lJ1wiNL5F6ObvbwKAayy4ZQpjd23ugm1NxqD01wPj2KlRKdAxgtbslT

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-03-29 17:39:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 233 (class 1259 OID 16506)
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    identification character varying(255) NOT NULL,
    password character varying(255),
    name character varying(255)
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16486)
-- Name: aplicacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aplicacion (
    id integer NOT NULL,
    date timestamp(6) without time zone,
    estado character varying(255),
    candidato_id bigint,
    puesto_id bigint
);


ALTER TABLE public.aplicacion OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16485)
-- Name: aplicacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aplicacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aplicacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16424)
-- Name: candidato; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidato (
    id bigint NOT NULL,
    approved boolean NOT NULL,
    cv_path character varying(255),
    email character varying(255),
    first_name character varying(255),
    identification character varying(255),
    last_name character varying(255),
    nationality character varying(255),
    password character varying(255),
    phone character varying(255),
    residence character varying(255)
);


ALTER TABLE public.candidato OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16434)
-- Name: candidato_caracteristica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.candidato_caracteristica (
    id bigint NOT NULL,
    level integer NOT NULL,
    candidato_id bigint,
    caracteristica_id bigint
);


ALTER TABLE public.candidato_caracteristica OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16433)
-- Name: candidato_caracteristica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.candidato_caracteristica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidato_caracteristica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16423)
-- Name: candidato_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.candidato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.candidato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16402)
-- Name: caracteristica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caracteristica (
    id bigint NOT NULL,
    parent_id bigint,
    name character varying(255)
);


ALTER TABLE public.caracteristica OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16401)
-- Name: caracteristica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caracteristica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caracteristica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16414)
-- Name: empresa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.empresa (
    id bigint NOT NULL,
    approved boolean NOT NULL,
    description character varying(1000),
    email character varying(255),
    location character varying(255),
    name character varying(255),
    password character varying(255),
    phone character varying(255)
);


ALTER TABLE public.empresa OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16413)
-- Name: empresa_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16452)
-- Name: puesto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.puesto (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    salary double precision NOT NULL,
    type character varying(255),
    empresa_id bigint
);


ALTER TABLE public.puesto OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16468)
-- Name: puesto_caracteristica; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.puesto_caracteristica (
    id bigint NOT NULL,
    required_level integer NOT NULL,
    caracteristica_id bigint,
    puesto_id bigint
);


ALTER TABLE public.puesto_caracteristica OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16467)
-- Name: puesto_caracteristica_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.puesto_caracteristica ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.puesto_caracteristica_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16451)
-- Name: puesto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.puesto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.puesto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4978 (class 0 OID 16506)
-- Dependencies: 233
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin (identification, password, name) FROM stdin;
admin1	$2a$10$GxtnfIH/LCM.KX4FYgvRiu0WQq4V2XE61rylRV0mf.LCc/4STX7nq	admin1
\.


--
-- TOC entry 4977 (class 0 OID 16486)
-- Dependencies: 232
-- Data for Name: aplicacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.aplicacion (id, date, estado, candidato_id, puesto_id) FROM stdin;
1	2026-03-29 17:29:53.02383	PENDIENTE	1	1
2	2026-03-29 17:36:14.678693	PENDIENTE	2	2
\.


--
-- TOC entry 4969 (class 0 OID 16424)
-- Dependencies: 224
-- Data for Name: candidato; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.candidato (id, approved, cv_path, email, first_name, identification, last_name, nationality, password, phone, residence) FROM stdin;
1	t	\N	jose@gmail.com	Jose	111	Castro	Costa Rica	$2a$10$DtUFmrXEuKgX0ADGis479.bu0QtUhFFHAen3qR.7v28UhrlKJmbUG	12345678	San José
2	t	\N	josue@gmail.com	Josué	222	Vargas	Costa Rica	$2a$10$tYoW73/ppynEpVXzXJtIEOx01B4xykZNJM4EPxKEgAc8KemR3pDiK	20244000	Heredia
\.


--
-- TOC entry 4971 (class 0 OID 16434)
-- Dependencies: 226
-- Data for Name: candidato_caracteristica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.candidato_caracteristica (id, level, candidato_id, caracteristica_id) FROM stdin;
1	3	1	2
2	2	1	3
3	5	1	4
4	5	2	1
5	5	2	3
6	5	2	4
7	3	2	6
\.


--
-- TOC entry 4965 (class 0 OID 16402)
-- Dependencies: 220
-- Data for Name: caracteristica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caracteristica (id, parent_id, name) FROM stdin;
1	\N	Python
2	\N	Java Script
3	\N	Docker
4	\N	Git
5	\N	C++
6	\N	C#
7	\N	HTML
8	\N	CSS
\.


--
-- TOC entry 4967 (class 0 OID 16414)
-- Dependencies: 222
-- Data for Name: empresa; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.empresa (id, approved, description, email, location, name, password, phone) FROM stdin;
1	t	Amazon :)	amazon@gmail.com	San José	Amazon	$2a$10$e2jDcry1bdndOqFEmyT4KumW4VT95Ym8Q.2pKrQwDtuZ2qocMaZoO	20244000
2	t	Microsoft :)	microsoft@gmail.com	San José	Microsoft	$2a$10$r3M5ua9t0NCkQ1AUBTuLC.9tLF1NRC7P12EOz1XAN4j/jc9wAuubm	22232000
\.


--
-- TOC entry 4973 (class 0 OID 16452)
-- Dependencies: 228
-- Data for Name: puesto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.puesto (id, active, created_at, description, salary, type, empresa_id) FROM stdin;
1	t	2026-03-29 17:29:21.125439	JS intern	1200	PUBLIC	1
2	t	2026-03-29 17:35:24.748024	Python senior and C# developer	5000	PUBLIC	2
\.


--
-- TOC entry 4975 (class 0 OID 16468)
-- Dependencies: 230
-- Data for Name: puesto_caracteristica; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.puesto_caracteristica (id, required_level, caracteristica_id, puesto_id) FROM stdin;
1	3	2	1
2	2	3	1
3	4	4	1
4	5	1	2
5	3	4	2
6	3	6	2
\.


--
-- TOC entry 4984 (class 0 OID 0)
-- Dependencies: 231
-- Name: aplicacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.aplicacion_id_seq', 2, true);


--
-- TOC entry 4985 (class 0 OID 0)
-- Dependencies: 225
-- Name: candidato_caracteristica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.candidato_caracteristica_id_seq', 7, true);


--
-- TOC entry 4986 (class 0 OID 0)
-- Dependencies: 223
-- Name: candidato_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.candidato_id_seq', 2, true);


--
-- TOC entry 4987 (class 0 OID 0)
-- Dependencies: 219
-- Name: caracteristica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caracteristica_id_seq', 8, true);


--
-- TOC entry 4988 (class 0 OID 0)
-- Dependencies: 221
-- Name: empresa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.empresa_id_seq', 2, true);


--
-- TOC entry 4989 (class 0 OID 0)
-- Dependencies: 229
-- Name: puesto_caracteristica_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.puesto_caracteristica_id_seq', 6, true);


--
-- TOC entry 4990 (class 0 OID 0)
-- Dependencies: 227
-- Name: puesto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.puesto_id_seq', 2, true);


--
-- TOC entry 4808 (class 2606 OID 16513)
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (identification);


--
-- TOC entry 4806 (class 2606 OID 16491)
-- Name: aplicacion aplicacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aplicacion
    ADD CONSTRAINT aplicacion_pkey PRIMARY KEY (id);


--
-- TOC entry 4796 (class 2606 OID 16440)
-- Name: candidato_caracteristica candidato_caracteristica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidato_caracteristica
    ADD CONSTRAINT candidato_caracteristica_pkey PRIMARY KEY (id);


--
-- TOC entry 4794 (class 2606 OID 16432)
-- Name: candidato candidato_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidato
    ADD CONSTRAINT candidato_pkey PRIMARY KEY (id);


--
-- TOC entry 4790 (class 2606 OID 16407)
-- Name: caracteristica caracteristica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caracteristica
    ADD CONSTRAINT caracteristica_pkey PRIMARY KEY (id);


--
-- TOC entry 4792 (class 2606 OID 16422)
-- Name: empresa empresa_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.empresa
    ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);


--
-- TOC entry 4802 (class 2606 OID 16474)
-- Name: puesto_caracteristica puesto_caracteristica_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto_caracteristica
    ADD CONSTRAINT puesto_caracteristica_pkey PRIMARY KEY (id);


--
-- TOC entry 4800 (class 2606 OID 16461)
-- Name: puesto puesto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto
    ADD CONSTRAINT puesto_pkey PRIMARY KEY (id);


--
-- TOC entry 4798 (class 2606 OID 16503)
-- Name: candidato_caracteristica unique_candidato_caracteristica; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidato_caracteristica
    ADD CONSTRAINT unique_candidato_caracteristica UNIQUE (candidato_id, caracteristica_id);


--
-- TOC entry 4804 (class 2606 OID 16505)
-- Name: puesto_caracteristica unique_puesto_caracteristica; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto_caracteristica
    ADD CONSTRAINT unique_puesto_caracteristica UNIQUE (puesto_id, caracteristica_id);


--
-- TOC entry 4815 (class 2606 OID 16497)
-- Name: aplicacion fk37tldcjqrbclbscvdug5r4u93; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aplicacion
    ADD CONSTRAINT fk37tldcjqrbclbscvdug5r4u93 FOREIGN KEY (puesto_id) REFERENCES public.puesto(id);


--
-- TOC entry 4809 (class 2606 OID 16408)
-- Name: caracteristica fk8m00d3j0f1nmedegqklm4vkuu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caracteristica
    ADD CONSTRAINT fk8m00d3j0f1nmedegqklm4vkuu FOREIGN KEY (parent_id) REFERENCES public.caracteristica(id);


--
-- TOC entry 4810 (class 2606 OID 16441)
-- Name: candidato_caracteristica fkf926dnnu0jr2vck16pj8ooiqc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidato_caracteristica
    ADD CONSTRAINT fkf926dnnu0jr2vck16pj8ooiqc FOREIGN KEY (candidato_id) REFERENCES public.candidato(id);


--
-- TOC entry 4813 (class 2606 OID 16480)
-- Name: puesto_caracteristica fkfroa3k0ispx4krbvv2fiipuea; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto_caracteristica
    ADD CONSTRAINT fkfroa3k0ispx4krbvv2fiipuea FOREIGN KEY (puesto_id) REFERENCES public.puesto(id);


--
-- TOC entry 4816 (class 2606 OID 16492)
-- Name: aplicacion fkh523kf2v708ivfjs0ubogrwr5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aplicacion
    ADD CONSTRAINT fkh523kf2v708ivfjs0ubogrwr5 FOREIGN KEY (candidato_id) REFERENCES public.candidato(id);


--
-- TOC entry 4811 (class 2606 OID 16446)
-- Name: candidato_caracteristica fkljn6avcvhk4ksl8t33pu1aokr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.candidato_caracteristica
    ADD CONSTRAINT fkljn6avcvhk4ksl8t33pu1aokr FOREIGN KEY (caracteristica_id) REFERENCES public.caracteristica(id);


--
-- TOC entry 4812 (class 2606 OID 16462)
-- Name: puesto fkn5jgwg4anw6yj1lrv2ii7es0a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto
    ADD CONSTRAINT fkn5jgwg4anw6yj1lrv2ii7es0a FOREIGN KEY (empresa_id) REFERENCES public.empresa(id);


--
-- TOC entry 4814 (class 2606 OID 16475)
-- Name: puesto_caracteristica fkr6awy7v36dp0uvwtkcg8m9d9k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puesto_caracteristica
    ADD CONSTRAINT fkr6awy7v36dp0uvwtkcg8m9d9k FOREIGN KEY (caracteristica_id) REFERENCES public.caracteristica(id);


-- Completed on 2026-03-29 17:39:38

--
-- PostgreSQL database dump complete
--

\unrestrict xcK3cXF5lJ1wiNL5F6ObvbwKAayy4ZQpjd23ugm1NxqD01wPj2KlRKdAxgtbslT

